# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-24 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('block', models.CharField(max_length=20, verbose_name='Building name')),
                ('room_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Room number')),
                ('floor_number', models.PositiveIntegerField(verbose_name='Floor number')),
                ('maximum_capacity', models.PositiveIntegerField(verbose_name='Maximum room size')),
                ('projector', models.CharField(max_length=20, verbose_name='Projector condition')),
                ('computer', models.CharField(max_length=20, verbose_name='Computer condition')),
                ('air_conditioner', models.CharField(max_length=20, verbose_name='AC condition')),
                ('speakers', models.CharField(max_length=20, verbose_name='Speakes condition')),
            ],
        ),
        migrations.CreateModel(
            name='labs',
            fields=[
                ('block', models.CharField(max_length=20, verbose_name='Building name')),
                ('room_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Room number')),
                ('floor_number', models.CharField(max_length=10, verbose_name='Floor number')),
                ('maximum_capacity', models.CharField(max_length=5, verbose_name='Maximum room size')),
                ('type', models.CharField(max_length=20, verbose_name='Type of Lab')),
                ('air_conditioner', models.CharField(max_length=20, verbose_name='AC condition')),
            ],
        ),
        migrations.CreateModel(
            name='request',
            fields=[
                ('block', models.CharField(max_length=20, verbose_name='Building name')),
                ('room_number', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Room number')),
                ('date', models.DateField(verbose_name='booking date')),
                ('time', models.TimeField(verbose_name='booking time')),
                ('reserved_by', models.CharField(max_length=10, verbose_name='reserver')),
                ('granter', models.CharField(max_length=10, verbose_name='granter')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('booking_status', models.IntegerField(verbose_name='booking status')),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='user id')),
                ('name', models.CharField(max_length=20, verbose_name='username')),
                ('phone', models.CharField(max_length=256, verbose_name='Phone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('type', models.CharField(max_length=10, verbose_name='type')),
            ],
        ),
    ]
