# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20170326_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='date',
            field=models.DateField(default='YYYY-MM-DD', verbose_name='booking date'),
        ),
    ]
