# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20170327_0211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='requestTable',
        ),
    ]
