# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-27 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_delete_requesttable'),
    ]

    operations = [
        migrations.CreateModel(
            name='requestTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=20, verbose_name='Building name')),
                ('room_number', models.CharField(max_length=10, verbose_name='Room number')),
                ('date', models.DateField(default='YYYY-MM-DD', verbose_name='booking date')),
                ('time', models.TimeField(verbose_name='booking time')),
                ('reserved_by', models.CharField(max_length=10, verbose_name='reserver')),
                ('granter', models.CharField(max_length=10, verbose_name='granter')),
                ('description', models.CharField(max_length=100, verbose_name='description')),
                ('booking_status', models.IntegerField(verbose_name='booking status')),
            ],
        ),
    ]
