# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_requesttable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='date',
            field=models.CharField(max_length=50, verbose_name='booking date'),
        ),
    ]
