# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20170403_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttable',
            name='time',
        ),
    ]
