# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_remove_requesttable_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='booking_status',
            field=models.CharField(max_length=50, verbose_name='booking status'),
        ),
    ]
