# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 13:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20170403_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requesttable',
            name='date',
        ),
        migrations.AddField(
            model_name='requesttable',
            name='endDateTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 18, 39, 43, 362280), verbose_name='endDateTime'),
        ),
        migrations.AddField(
            model_name='requesttable',
            name='startDateTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 18, 39, 43, 362280), verbose_name='startDateTime'),
        ),
    ]
