# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 13:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20170403_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='endDateTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 13, 14, 22, 208580, tzinfo=utc), verbose_name='endDateTime'),
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='startDateTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 13, 14, 22, 208580, tzinfo=utc), verbose_name='startDateTime'),
        ),
    ]
