# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0011_auto_20170403_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='booking_status',
            field=models.CharField(default=0, max_length=1, verbose_name='booking status'),
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='endDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='endDateTime'),
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='startDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='startDateTime'),
        ),
    ]
