# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_auto_20170403_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='endDateTime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='endDateTime'),
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='startDateTime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='startDateTime'),
        ),
    ]
