# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_auto_20170403_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttable',
            name='endDateTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 17, 21, 34, 773794, tzinfo=utc), verbose_name='endDateTime'),
        ),
        migrations.AlterField(
            model_name='requesttable',
            name='startDateTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 4, 3, 17, 21, 34, 773794, tzinfo=utc), verbose_name='startDateTime'),
        ),
    ]
